<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rabuclearchevron_leftSEPchevron_right14_13cb66</name>
   <tag></tag>
   <elementGuidId>ee1d49b0-7679-4d68-94d5-b5602d8b96e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dtp_gQjRs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dtp_gQjRs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dtp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dtp_gQjRs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rabuclearchevron_leftSEPchevron_right14chevron_left2022chevron_right23:55September 2022SSRKJSM010203040506070809101112131415161718192021222324252627282930AMPMkeyboard_arrow_up2019202020212022202320242025keyboard_arrow_downSekarangBersihBatalPilih</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dtp_gQjRs&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dtp_gQjRs']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dtp_gQjRs' and (text() = 'Rabuclearchevron_leftSEPchevron_right14chevron_left2022chevron_right23:55September 2022SSRKJSM010203040506070809101112131415161718192021222324252627282930AMPMkeyboard_arrow_up2019202020212022202320242025keyboard_arrow_downSekarangBersihBatalPilih' or . = 'Rabuclearchevron_leftSEPchevron_right14chevron_left2022chevron_right23:55September 2022SSRKJSM010203040506070809101112131415161718192021222324252627282930AMPMkeyboard_arrow_up2019202020212022202320242025keyboard_arrow_downSekarangBersihBatalPilih')]</value>
   </webElementXpaths>
</WebElementEntity>
