<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ALTOPAYAMAR INDONESIAANZ INDONESIAAT_0a9357</name>
   <tag></tag>
   <elementGuidId>e434feac-b5fb-4d2f-938c-42cfe54ed01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bankAccountBankId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bankAccountBankId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bankAccountBankId</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bankAccount.bank.id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ms show-tick is-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tidak ada yang dipilih</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-subtext</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        ALTOPAY
AMAR INDONESIA
ANZ INDONESIA
ATMB LSB
BANGKOK BANK PUBLIC CO.LTD.
BANK ANDA
BANK ARTHA GRAHA INTERNASIONAL
BANK BCA SYARIAH
BANK BISNIS INTERNASIONAL
BANK BNP PARIBAS INDONESIA
BANK CAPITAL INDONESIA
BANK CENTRAL ASIA (BCA)
BANK CHINA CONSTRUCTION BANK INDONESIA
BANK CIMB NIAGA
BANK CIMB NIAGA UNIT USAHA SYARIAH
BANK COMMONWEALTH
BANK CTBC
BANK DANAMON INDONESIA
BANK DANAMON SYARIAH
BANK DBS INDONESIA
BANK DKI
BANK DKI UNIT USAHA SYARIAH
BANK FAMA INTERNASIONAL
BANK GANESHA
BANK HARDA
BANK HSBC INDONESIA
BANK ICBC INDONESIA
BANK INA PERDANA
BANK INDEX SELINDO
BANK JABAR BANTEN SYARIAH
BANK JAGO/JAGO SYARIAH
BANK JTRUST INDONESIA
BANK MANDIRI
BANK MANDIRI TASPEN POS
BANK MASPION INDONESIA
BANK MAYAPADA INTERNASIONAL
BANK MAYBANK INDONESIA
BANK MAYORA
BANK MEGA
BANK MESTIKA DHARMA
BANK MITRANIAGA
BANK MIZUHO INDONESIA
BANK MNC INTERNASIONAL
BANK MUAMALAT INDONESIA
BANK MULTIARTA SENTOSA
BANK NAGARI
BANK NATIONALNOBU
BANK NEGARA INDONESIA (BNI)
BANK NUSANTARA PARAHYANGAN
BANK OCBC NISP
BANK OCBC NISP, TBK UNIT USAHA SYARIAH
BANK OF AMERICA, N.A
BANK OF CHINA (HONGKONG) LIMITED
BANK OF INDIA INDONESIA
BANK OKE
BANK OKE INDONESIA
BANK PANIN DUBAI SYARIAH
BANK PEMBANGUNAN DAERAH ACEH
BANK PEMBANGUNAN DAERAH BALI
BANK PEMBANGUNAN DAERAH BANTEN
BANK PEMBANGUNAN DAERAH BENGKULU
BANK PEMBANGUNAN DAERAH JAMBI
BANK PEMBANGUNAN DAERAH JAWA BARAT DAN BANTEN
BANK PEMBANGUNAN DAERAH JAWA TENGAH
BANK PEMBANGUNAN DAERAH JAWA TIMUR
BANK PEMBANGUNAN DAERAH KALIMANTAN BARAT
BANK PEMBANGUNAN DAERAH KALIMANTAN SELATAN
BANK PEMBANGUNAN DAERAH KALIMANTAN TENGAH
BANK PEMBANGUNAN DAERAH KALIMANTAN TIMUR DAN KALIMANTAN UTARA
BANK PEMBANGUNAN DAERAH LAMPUNG
BANK PEMBANGUNAN DAERAH MALUKU
BANK PEMBANGUNAN DAERAH NUSA TENGGARA BARAT
BANK PEMBANGUNAN DAERAH NUSA TENGGARA TIMUR
BANK PEMBANGUNAN DAERAH PAPUA
BANK PEMBANGUNAN DAERAH RIAU
BANK PEMBANGUNAN DAERAH SULAWESI SELATAN BARAT
BANK PEMBANGUNAN DAERAH SULAWESI TENGAH
BANK PEMBANGUNAN DAERAH SULAWESI TENGGARA
BANK PEMBANGUNAN DAERAH SULAWESI UTARA
BANK PEMBANGUNAN DAERAH SUMATERA UTARA
BANK PEMBANGUNAN DAERAH SUMSEL DAN BABEL
BANK PEMBANGUNAN DAERAH YOGYAKARTA
BANK PERMATA
BANK PERMATA, TBK UNIT USAHA SYARIAH
BANK QNB INDONESIA
BANK RAKYAT INDONESIA AGRONIAGA
BANK RAKYAT INDONESIA (BRI)
BANK RESONA PERDANIA
BANK ROYAL INDONESIA
BANK SAHABAT SAMPOERNA
BANK SBII
BANK SHINHAN INDONESIA
BANK SINARMAS
BANK SINARMAS UNIT USAHA SYARIAH
BANK SUMITOMO MITSUI INDONESIA
BANK SYARIAH BUKOPIN
BANK SYARIAH MEGA INDONESIA
BANK TABUNGAN NEGARA (BTN)
BANK TABUNGAN NEGARA (PERSERO), TBK UNIT USAHA SYARIAH
BANK TABUNGAN PENSIUNAN NASIONAL (BTPN)
BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH
BANK UOB INDONESIA
BANK VICTORIA INTERNATIONAL
BANK WOORI SAUDARA INDONESIA 1906
BANK YUDHA BHAKTI
BPD JAWA TENGAH UNIT USAHA SYARIAH
BPD JAWA TIMUR UNIT USAHA SYARIAH
BPD KALIMANTAN BARAT UNIT USAHA SYARIAH
BPD KALIMANTAN SELATAN UNIT USAHA SYARIAH
BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA UNIT USAHA SYARIAH
BPD SULAWESI SELATAN BARAT UU SYARIAH
BPD SUMATERA BARAT UNIT USAHA SYARIAH
BPD SUMATERA UTARA UNIT USAHA SYARIAH
BPD YOGYAKARTA UNIT USAHA SYARIAH
BSI
BSI EX BNIS
BSI EX BRIS
BSI EX BSM
BUMI ARTA
CENTRATAMA NASIONAL BANK
CITIBANK N.A.
DEUTSCHE BANK AG
DOKU
FINNET
IBK INDONESIA
IMKAS
JASA JAKARTA
JP MORGAN CHASE BANK, N.A.
KB BUKOPIN
KEB HANA
MAYBANK SYARIAH INDONESIA
PAN INDONESIA BANK (PANIN)
PRIMA MASTER BANK
SEABANK
SGODPAY
STANDARD CHARTERED BANK
TELKOM
THE BANK OF TOKYO MITSUBISHI UFJ, LTD
THE ROYAL BANK OF SCOTLAND, N.V
VICTORIA SYR
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankAccountBankId&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bankAccountBankId']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='dashboardForm-p-2']/div/div/div/div/div/div[2]/div/div[2]/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Bank'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Rekening Bank'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak ada yang dipilih'])[11]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANK BCA SYARIAH'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/div/div/div/div[2]/div/div[2]/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'bankAccountBankId' and @name = 'bankAccount.bank.id' and @title = 'Tidak ada yang dipilih' and (text() = '
                                                                        ALTOPAY
AMAR INDONESIA
ANZ INDONESIA
ATMB LSB
BANGKOK BANK PUBLIC CO.LTD.
BANK ANDA
BANK ARTHA GRAHA INTERNASIONAL
BANK BCA SYARIAH
BANK BISNIS INTERNASIONAL
BANK BNP PARIBAS INDONESIA
BANK CAPITAL INDONESIA
BANK CENTRAL ASIA (BCA)
BANK CHINA CONSTRUCTION BANK INDONESIA
BANK CIMB NIAGA
BANK CIMB NIAGA UNIT USAHA SYARIAH
BANK COMMONWEALTH
BANK CTBC
BANK DANAMON INDONESIA
BANK DANAMON SYARIAH
BANK DBS INDONESIA
BANK DKI
BANK DKI UNIT USAHA SYARIAH
BANK FAMA INTERNASIONAL
BANK GANESHA
BANK HARDA
BANK HSBC INDONESIA
BANK ICBC INDONESIA
BANK INA PERDANA
BANK INDEX SELINDO
BANK JABAR BANTEN SYARIAH
BANK JAGO/JAGO SYARIAH
BANK JTRUST INDONESIA
BANK MANDIRI
BANK MANDIRI TASPEN POS
BANK MASPION INDONESIA
BANK MAYAPADA INTERNASIONAL
BANK MAYBANK INDONESIA
BANK MAYORA
BANK MEGA
BANK MESTIKA DHARMA
BANK MITRANIAGA
BANK MIZUHO INDONESIA
BANK MNC INTERNASIONAL
BANK MUAMALAT INDONESIA
BANK MULTIARTA SENTOSA
BANK NAGARI
BANK NATIONALNOBU
BANK NEGARA INDONESIA (BNI)
BANK NUSANTARA PARAHYANGAN
BANK OCBC NISP
BANK OCBC NISP, TBK UNIT USAHA SYARIAH
BANK OF AMERICA, N.A
BANK OF CHINA (HONGKONG) LIMITED
BANK OF INDIA INDONESIA
BANK OKE
BANK OKE INDONESIA
BANK PANIN DUBAI SYARIAH
BANK PEMBANGUNAN DAERAH ACEH
BANK PEMBANGUNAN DAERAH BALI
BANK PEMBANGUNAN DAERAH BANTEN
BANK PEMBANGUNAN DAERAH BENGKULU
BANK PEMBANGUNAN DAERAH JAMBI
BANK PEMBANGUNAN DAERAH JAWA BARAT DAN BANTEN
BANK PEMBANGUNAN DAERAH JAWA TENGAH
BANK PEMBANGUNAN DAERAH JAWA TIMUR
BANK PEMBANGUNAN DAERAH KALIMANTAN BARAT
BANK PEMBANGUNAN DAERAH KALIMANTAN SELATAN
BANK PEMBANGUNAN DAERAH KALIMANTAN TENGAH
BANK PEMBANGUNAN DAERAH KALIMANTAN TIMUR DAN KALIMANTAN UTARA
BANK PEMBANGUNAN DAERAH LAMPUNG
BANK PEMBANGUNAN DAERAH MALUKU
BANK PEMBANGUNAN DAERAH NUSA TENGGARA BARAT
BANK PEMBANGUNAN DAERAH NUSA TENGGARA TIMUR
BANK PEMBANGUNAN DAERAH PAPUA
BANK PEMBANGUNAN DAERAH RIAU
BANK PEMBANGUNAN DAERAH SULAWESI SELATAN BARAT
BANK PEMBANGUNAN DAERAH SULAWESI TENGAH
BANK PEMBANGUNAN DAERAH SULAWESI TENGGARA
BANK PEMBANGUNAN DAERAH SULAWESI UTARA
BANK PEMBANGUNAN DAERAH SUMATERA UTARA
BANK PEMBANGUNAN DAERAH SUMSEL DAN BABEL
BANK PEMBANGUNAN DAERAH YOGYAKARTA
BANK PERMATA
BANK PERMATA, TBK UNIT USAHA SYARIAH
BANK QNB INDONESIA
BANK RAKYAT INDONESIA AGRONIAGA
BANK RAKYAT INDONESIA (BRI)
BANK RESONA PERDANIA
BANK ROYAL INDONESIA
BANK SAHABAT SAMPOERNA
BANK SBII
BANK SHINHAN INDONESIA
BANK SINARMAS
BANK SINARMAS UNIT USAHA SYARIAH
BANK SUMITOMO MITSUI INDONESIA
BANK SYARIAH BUKOPIN
BANK SYARIAH MEGA INDONESIA
BANK TABUNGAN NEGARA (BTN)
BANK TABUNGAN NEGARA (PERSERO), TBK UNIT USAHA SYARIAH
BANK TABUNGAN PENSIUNAN NASIONAL (BTPN)
BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH
BANK UOB INDONESIA
BANK VICTORIA INTERNATIONAL
BANK WOORI SAUDARA INDONESIA 1906
BANK YUDHA BHAKTI
BPD JAWA TENGAH UNIT USAHA SYARIAH
BPD JAWA TIMUR UNIT USAHA SYARIAH
BPD KALIMANTAN BARAT UNIT USAHA SYARIAH
BPD KALIMANTAN SELATAN UNIT USAHA SYARIAH
BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA UNIT USAHA SYARIAH
BPD SULAWESI SELATAN BARAT UU SYARIAH
BPD SUMATERA BARAT UNIT USAHA SYARIAH
BPD SUMATERA UTARA UNIT USAHA SYARIAH
BPD YOGYAKARTA UNIT USAHA SYARIAH
BSI
BSI EX BNIS
BSI EX BRIS
BSI EX BSM
BUMI ARTA
CENTRATAMA NASIONAL BANK
CITIBANK N.A.
DEUTSCHE BANK AG
DOKU
FINNET
IBK INDONESIA
IMKAS
JASA JAKARTA
JP MORGAN CHASE BANK, N.A.
KB BUKOPIN
KEB HANA
MAYBANK SYARIAH INDONESIA
PAN INDONESIA BANK (PANIN)
PRIMA MASTER BANK
SEABANK
SGODPAY
STANDARD CHARTERED BANK
TELKOM
THE BANK OF TOKYO MITSUBISHI UFJ, LTD
THE ROYAL BANK OF SCOTLAND, N.V
VICTORIA SYR
' or . = '
                                                                        ALTOPAY
AMAR INDONESIA
ANZ INDONESIA
ATMB LSB
BANGKOK BANK PUBLIC CO.LTD.
BANK ANDA
BANK ARTHA GRAHA INTERNASIONAL
BANK BCA SYARIAH
BANK BISNIS INTERNASIONAL
BANK BNP PARIBAS INDONESIA
BANK CAPITAL INDONESIA
BANK CENTRAL ASIA (BCA)
BANK CHINA CONSTRUCTION BANK INDONESIA
BANK CIMB NIAGA
BANK CIMB NIAGA UNIT USAHA SYARIAH
BANK COMMONWEALTH
BANK CTBC
BANK DANAMON INDONESIA
BANK DANAMON SYARIAH
BANK DBS INDONESIA
BANK DKI
BANK DKI UNIT USAHA SYARIAH
BANK FAMA INTERNASIONAL
BANK GANESHA
BANK HARDA
BANK HSBC INDONESIA
BANK ICBC INDONESIA
BANK INA PERDANA
BANK INDEX SELINDO
BANK JABAR BANTEN SYARIAH
BANK JAGO/JAGO SYARIAH
BANK JTRUST INDONESIA
BANK MANDIRI
BANK MANDIRI TASPEN POS
BANK MASPION INDONESIA
BANK MAYAPADA INTERNASIONAL
BANK MAYBANK INDONESIA
BANK MAYORA
BANK MEGA
BANK MESTIKA DHARMA
BANK MITRANIAGA
BANK MIZUHO INDONESIA
BANK MNC INTERNASIONAL
BANK MUAMALAT INDONESIA
BANK MULTIARTA SENTOSA
BANK NAGARI
BANK NATIONALNOBU
BANK NEGARA INDONESIA (BNI)
BANK NUSANTARA PARAHYANGAN
BANK OCBC NISP
BANK OCBC NISP, TBK UNIT USAHA SYARIAH
BANK OF AMERICA, N.A
BANK OF CHINA (HONGKONG) LIMITED
BANK OF INDIA INDONESIA
BANK OKE
BANK OKE INDONESIA
BANK PANIN DUBAI SYARIAH
BANK PEMBANGUNAN DAERAH ACEH
BANK PEMBANGUNAN DAERAH BALI
BANK PEMBANGUNAN DAERAH BANTEN
BANK PEMBANGUNAN DAERAH BENGKULU
BANK PEMBANGUNAN DAERAH JAMBI
BANK PEMBANGUNAN DAERAH JAWA BARAT DAN BANTEN
BANK PEMBANGUNAN DAERAH JAWA TENGAH
BANK PEMBANGUNAN DAERAH JAWA TIMUR
BANK PEMBANGUNAN DAERAH KALIMANTAN BARAT
BANK PEMBANGUNAN DAERAH KALIMANTAN SELATAN
BANK PEMBANGUNAN DAERAH KALIMANTAN TENGAH
BANK PEMBANGUNAN DAERAH KALIMANTAN TIMUR DAN KALIMANTAN UTARA
BANK PEMBANGUNAN DAERAH LAMPUNG
BANK PEMBANGUNAN DAERAH MALUKU
BANK PEMBANGUNAN DAERAH NUSA TENGGARA BARAT
BANK PEMBANGUNAN DAERAH NUSA TENGGARA TIMUR
BANK PEMBANGUNAN DAERAH PAPUA
BANK PEMBANGUNAN DAERAH RIAU
BANK PEMBANGUNAN DAERAH SULAWESI SELATAN BARAT
BANK PEMBANGUNAN DAERAH SULAWESI TENGAH
BANK PEMBANGUNAN DAERAH SULAWESI TENGGARA
BANK PEMBANGUNAN DAERAH SULAWESI UTARA
BANK PEMBANGUNAN DAERAH SUMATERA UTARA
BANK PEMBANGUNAN DAERAH SUMSEL DAN BABEL
BANK PEMBANGUNAN DAERAH YOGYAKARTA
BANK PERMATA
BANK PERMATA, TBK UNIT USAHA SYARIAH
BANK QNB INDONESIA
BANK RAKYAT INDONESIA AGRONIAGA
BANK RAKYAT INDONESIA (BRI)
BANK RESONA PERDANIA
BANK ROYAL INDONESIA
BANK SAHABAT SAMPOERNA
BANK SBII
BANK SHINHAN INDONESIA
BANK SINARMAS
BANK SINARMAS UNIT USAHA SYARIAH
BANK SUMITOMO MITSUI INDONESIA
BANK SYARIAH BUKOPIN
BANK SYARIAH MEGA INDONESIA
BANK TABUNGAN NEGARA (BTN)
BANK TABUNGAN NEGARA (PERSERO), TBK UNIT USAHA SYARIAH
BANK TABUNGAN PENSIUNAN NASIONAL (BTPN)
BANK TABUNGAN PENSIUNAN NASIONAL SYARIAH
BANK UOB INDONESIA
BANK VICTORIA INTERNATIONAL
BANK WOORI SAUDARA INDONESIA 1906
BANK YUDHA BHAKTI
BPD JAWA TENGAH UNIT USAHA SYARIAH
BPD JAWA TIMUR UNIT USAHA SYARIAH
BPD KALIMANTAN BARAT UNIT USAHA SYARIAH
BPD KALIMANTAN SELATAN UNIT USAHA SYARIAH
BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA UNIT USAHA SYARIAH
BPD SULAWESI SELATAN BARAT UU SYARIAH
BPD SUMATERA BARAT UNIT USAHA SYARIAH
BPD SUMATERA UTARA UNIT USAHA SYARIAH
BPD YOGYAKARTA UNIT USAHA SYARIAH
BSI
BSI EX BNIS
BSI EX BRIS
BSI EX BSM
BUMI ARTA
CENTRATAMA NASIONAL BANK
CITIBANK N.A.
DEUTSCHE BANK AG
DOKU
FINNET
IBK INDONESIA
IMKAS
JASA JAKARTA
JP MORGAN CHASE BANK, N.A.
KB BUKOPIN
KEB HANA
MAYBANK SYARIAH INDONESIA
PAN INDONESIA BANK (PANIN)
PRIMA MASTER BANK
SEABANK
SGODPAY
STANDARD CHARTERED BANK
TELKOM
THE BANK OF TOKYO MITSUBISHI UFJ, LTD
THE ROYAL BANK OF SCOTLAND, N.V
VICTORIA SYR
')]</value>
   </webElementXpaths>
</WebElementEntity>
